### ISSUE TITLE
"Login via Browser" doesn't work-"通过浏览器登陆"选项不起作用

### ISSUE THREAD

**Issue by luciferseraph** [sffxzzp/TTVDropBot-Build#1]
Choose "Login via Browser", Chrome browser poped up, but when click "logging in", it will show error message like below, and I didn't recevie the Verification Code in my mailbox. When changing to "Directly via Command Line", it works fine.

![$900L@4}7GY016MI6(N2U0C](https://user-images.githubusercontent.com/9167487/191662749-7b46ed22-4221-4ca2-8257-bffdd576bf9f.png)

**Comment by sffxzzp** [comment]
Have you tried binaries of the original [Zaarrg/TTVDropBot](https://github.com/Zaarrg/TTVDropBot) repo?
I have the same issue, So I think it is the `puppeteer` requirement that needs specified version of chrome to work correctly.
Instead of using login, you could copy auth-token from your browser cookies, and place it into `twitch-session.json`.
