### ISSUE TITLE
[docker] Freezing after watching for 10 minutes

### ISSUE THREAD

**Issue by thierrybla** [sffxzzp/TTVDropBot-Build#2]
Hi, I noticed that it will watch a drop once but after that It just freezes when going to the next stream.
Does anyone else experience this issue?

At this moment it is stuck on "Watching in 45 seconds..." once in a while it will look for the drops progress but then be stuck on "watching in 45 seconds..." again. I don't see my drops progress increasing either.

**Comment by sffxzzp** [comment]
Any screenshots?
For now, ttvdropbot or any other fork can't pass the integrity check, so that you have to set the `autoclaim` and `autopoints` to false.

And if you have only a few game in priority list, it may stuck because the program can't claim the drop, and with no other game in the list, it'll loop until you claim it by hands or userscripts.

**Comment by sffxzzp** [comment]
See `notice` part of [README.md](https://github.com/PockySweet/Enhanced-TTVDropBot/blob/main/readme.md) of PockySweet/Enhanced-TTVDropBot for more detail.
